# Generated by Django 4.0.2 on 2022-02-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='images.jpg', null=True, upload_to=''),
        ),
    ]
