# Generated by Django 4.0.2 on 2022-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
