# Generated by Django 4.0.2 on 2022-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_room_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
