# Generated by Django 4.0.2 on 2022-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_room_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
