# Generated by Django 4.0.2 on 2022-04-30 11:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_room_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
