# Generated by Django 4.0.4 on 2022-05-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_room_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'Topic'},
        ),
    ]
