# Generated by Django 4.0.4 on 2022-05-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
