# Generated by Django 4.0.4 on 2022-05-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_room_topic_alter_topics_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.topic'),
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
