# Generated by Django 4.0.4 on 2022-05-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
    ]
